mutation CreateGroup {
    static: createParticipantGroup(input: {
        title: "static-group",
        description: "static-group-desc",
        type: STATIC
    }) {
        ...PG
    },
    dynamic: createParticipantGroup(input: {
        title: "static-group",
        description: "static-group-desc",
        type: DYNAMIC
    }) {
        ...PG
    }
}

fragment PG on CreateParticipantGroupPayload {
    participantGroup {
        id
        version
        type
        title
        description
        created
        createdBy {
            id
            email
        }
        memberIds
        membersPage {
            participants {
                id
                firstName
                lastName
            }
            pagination {
                totalCount
            }
        }
    }
}