mutation UpdateParticipantGroupMemberFilter {
    updateParticipantGroupMemberFilter(input: {
        id: "a60009d1-f992-47c7-a811-e9d0f1e7b7ea",
        version: 1,
        participantFilter: "{\"field\": \"firstName\", \"operator\": \"EQ\", \"value\": \"Piotr\"}"
    }) {
        participantGroup {
            id
            version
            type
            title
            description
            created
            createdBy {
                id
                email
            }
            memberFilter
            membersPage(
                filter: "{\"field\": \"lastName\", \"operator\": \"EQ\", \"value\": \"Kozak\"}",
                orderBy: {direction: ASC, field: "firstName"},
                offsetAndLimit: {offset: 0, limit: 2}) {
                pagination {
                    totalCount
                }
                participants {
                    id
                    firstName
                    lastName
                }
            }
        }
    }
}