mutation CreateStaticGroup {
    updateParticipantGroupMembers(input: {
        id: "a60009d1-f992-47c7-a811-e9d0f1e7b7ea",
        version: 3,
        participantIds: ["8b03b1e3-e862-4092-8731-e25829c2d26d"]
    }) {
        participantGroup {
            id
            version
            type
            title
            description
            created
            membersPage {
                pagination {
                    totalCount
                }
                participants {
                    id
                    firstName
                    lastName
                }
            }
            createdBy {
                id
                email
            }
            memberIds
        }
    }
}