mutation UpdateParticipantGroupMemberFilter {
    updateParticipantGroupMemberFilter(input: {
        id: "060a44ce-697a-49a2-83c6-32a5bac8593b",
        version: 0,
        participantFilter: "{\"items\": [{\"field\": \"firstName\", \"operator\": \"EQ\", \"value\": \"Piotr\"},{\"field\": \"firstName\", \"operator\": \"EQ\", \"value\": \"Piotr\"}], \"operator\": \"OR\"}"
    }) {
        participantGroup {
            id
            version
            type
            title
            description
            created
            createdBy {
                id
                email
            }
            memberFilter
            membersPage(
                filter: "{\"field\": \"lastName\", \"operator\": \"EQ\", \"value\": \"Kozak\"}",
                orderBy: {direction: ASC, field: "firstName"},
                offsetAndLimit: {offset: 0, limit: 2}) {
                pagination {
                    totalCount
                }
                participants {
                    id
                    firstName
                    lastName
                }
            }
        }
    }
}
